version: '3.8'

services:
  poker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poker
    ports:
      - "6080:8080"
#      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    restart: unless-stopped
